version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.0.1.9 
      KAFKA_ZOOKEEPER_CONNECT: 10.0.1.9:2181
  kafdrop:
    container_name: kafdrop
    image: obsidiandynamics/kafdrop:latest
    environment:
      KAFKA_BROKERCONNECT: 10.0.1.9:9092
    ports:
      - 9000:9000
    depends_on:
      - kafka 
